name: Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          BASE_VERSION=$(git describe --tags --always)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          CLEAN_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9.-]/-/g')

          if [ "$BRANCH_NAME" != "main" ]; then
            RELEASE_VERSION="${BASE_VERSION}+${CLEAN_BRANCH}"
            COMMIT_VERSION="${BASE_VERSION}+${BRANCH_NAME}"
          else
            RELEASE_VERSION="$BASE_VERSION"
            COMMIT_VERSION="$BASE_VERSION"
          fi

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

          cat > reframework/autorun/HudController/config/version.lua << EOF
          return {
              version = "$(git describe --tags --abbrev=0)",
              commit = "$COMMIT_VERSION",
          }
          EOF

          zip -r "HudController-${RELEASE_VERSION}.zip" reframework/
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          repo: HudController-releases
          owner: kmy0
          token: ${{ secrets.RELEASE_REPO_TOKEN }}
          name: "${{ env.RELEASE_VERSION }}"
          tag: "${{ env.RELEASE_VERSION }}"
          artifacts: "HudController-*.zip"
          makeLatest: true